#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/map-codebase.sh --root <project-root>
USAGE
}

ROOT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      ROOT="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -z "${ROOT}" ]]; then
  echo "Error: --root is required." >&2
  usage
  exit 2
fi

ROOT="$(cd "${ROOT}" && pwd)"
DISCOVERY_DIR="${ROOT}/sdd/memory-bank/discovery"
ARCHIVE_ROOT="${DISCOVERY_DIR}/archive"
timestamp="$(date +%Y%m%d-%H%M%S)"

mkdir -p "${DISCOVERY_DIR}" "${ARCHIVE_ROOT}"

current_files=(
  "stack.md"
  "architecture.md"
  "structure.md"
  "conventions.md"
  "testing.md"
  "integrations.md"
  "concerns.md"
)

has_existing=0
for f in "${current_files[@]}"; do
  if [[ -f "${DISCOVERY_DIR}/${f}" && -s "${DISCOVERY_DIR}/${f}" ]]; then
    has_existing=1
    break
  fi
done

if [[ ${has_existing} -eq 1 ]]; then
  archive_dir="${ARCHIVE_ROOT}/${timestamp}"
  mkdir -p "${archive_dir}"
  for f in "${current_files[@]}"; do
    [[ -f "${DISCOVERY_DIR}/${f}" ]] || continue
    cp "${DISCOVERY_DIR}/${f}" "${archive_dir}/${f}"
  done
fi

detect_stack() {
  if [[ -f "${ROOT}/package.json" ]]; then
    echo "- Language: JavaScript/TypeScript (detected via package.json)"
  fi
  if [[ -f "${ROOT}/pyproject.toml" || -f "${ROOT}/requirements.txt" ]]; then
    echo "- Language: Python"
  fi
  if [[ -f "${ROOT}/go.mod" ]]; then
    echo "- Language: Go"
  fi
  if [[ -f "${ROOT}/Cargo.toml" ]]; then
    echo "- Language: Rust"
  fi
  if [[ -f "${ROOT}/pom.xml" || -f "${ROOT}/build.gradle" || -f "${ROOT}/build.gradle.kts" ]]; then
    echo "- Language: JVM"
  fi
  if [[ -f "${ROOT}/Gemfile" ]]; then
    echo "- Language: Ruby"
  fi

  return 0
}

top_dirs="$(find "${ROOT}" -maxdepth 1 -mindepth 1 -type d \
  ! -name '.git' ! -name 'node_modules' ! -name 'dist' ! -name 'build' ! -name '.next' \
  ! -name 'sdd' ! -name '.cursor' ! -name '.windsurf' ! -name '.agent' \
  -exec basename {} \; | sort | sed 's/^/- /')"

test_files="$(find "${ROOT}" -type f \( -name '*test*' -o -name '*spec*' -o -path '*/tests/*' -o -path '*/test/*' \) \
  ! -path '*/node_modules/*' ! -path '*/.git/*' ! -path '*/sdd/*' ! -path '*/.cursor/*' ! -path '*/.windsurf/*' ! -path '*/.agent/*' \
  | sed "s#${ROOT}/#- #" | sort | head -20)"

workflow_files="$(
  if [[ -d "${ROOT}/.github/workflows" ]]; then
    find "${ROOT}/.github/workflows" -type f | sed "s#${ROOT}/#- #" | sort
  fi
)"
todo_hits="$(rg -n "TODO|FIXME|XXX" "${ROOT}" \
  -g '!node_modules/**' -g '!.git/**' -g '!dist/**' -g '!build/**' \
  -g '!sdd/**' -g '!.cursor/**' -g '!.windsurf/**' -g '!.agent/**' \
  2>/dev/null | head -20 | sed 's#^#- #' || true)"

cat > "${DISCOVERY_DIR}/stack.md" <<EOF
# Discovery Stack

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Signals
$(detect_stack)
EOF

cat > "${DISCOVERY_DIR}/architecture.md" <<EOF
# Discovery Architecture

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Signals
$(if [[ -d "${ROOT}/app" ]]; then echo "- \`app/\` exists"; fi)
$(if [[ -d "${ROOT}/docs" ]]; then echo "- \`docs/\` exists"; fi)
$(if [[ -d "${ROOT}/scripts" ]]; then echo "- \`scripts/\` exists"; fi)
$(if [[ -f "${ROOT}/docker-compose.yml" || -f "${ROOT}/compose.yaml" ]]; then echo "- Container orchestration file detected"; fi)
EOF

cat > "${DISCOVERY_DIR}/structure.md" <<EOF
# Discovery Structure

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Top-Level Directories
${top_dirs:-"- (none detected)"}
EOF

cat > "${DISCOVERY_DIR}/conventions.md" <<EOF
# Discovery Conventions

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Signals
$(if [[ -f "${ROOT}/.editorconfig" ]]; then echo "- .editorconfig present"; fi)
$(if [[ -f "${ROOT}/package.json" ]]; then echo "- package.json present"; fi)
$(if [[ -f "${ROOT}/Makefile" ]]; then echo "- Makefile present"; fi)
EOF

cat > "${DISCOVERY_DIR}/testing.md" <<EOF
# Discovery Testing

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Test Files
${test_files:-"- No test files detected with simple heuristics"}
EOF

cat > "${DISCOVERY_DIR}/integrations.md" <<EOF
# Discovery Integrations

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Automation
${workflow_files:-"- No GitHub workflow files detected"}

## Runtime Signals
$(if [[ -f "${ROOT}/Dockerfile" ]]; then echo "- Dockerfile present"; fi)
$(if [[ -f "${ROOT}/.env.example" || -f "${ROOT}/.env" ]]; then echo "- Environment file present"; fi)
EOF

cat > "${DISCOVERY_DIR}/concerns.md" <<EOF
# Discovery Concerns

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Potential Follow-Ups
${todo_hits:-"- No TODO/FIXME markers detected with simple heuristics"}

## Reminder
- Treat discovery output as unconfirmed until intake or discussion records it explicitly.
EOF

echo "Codebase mapping: OK"
