#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/map-codebase.sh --root <project-root> [--spectra-root <spectra-root>] [--preserve-reviewed]

--preserve-reviewed keeps an existing business domain index and technical module index (reviewed project
intelligence); only repository-derived discovery files are regenerated.
USAGE
}

ROOT=""
SPECTRA_ROOT=""
PRESERVE_REVIEWED=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      ROOT="${2:-}"
      shift 2
      ;;
    --spectra-root)
      SPECTRA_ROOT="${2:-}"
      shift 2
      ;;
    --preserve-reviewed)
      PRESERVE_REVIEWED=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -z "${ROOT}" ]]; then
  echo "Error: --root is required." >&2
  usage
  exit 2
fi

ROOT="$(cd "${ROOT}" && pwd)"
if [[ -z "${SPECTRA_ROOT}" ]]; then
  SPECTRA_ROOT="${SPECTRA_REPO_ROOT:-${ROOT}}"
fi
SPECTRA_ROOT="$(cd "${SPECTRA_ROOT}" && pwd)"
DISCOVERY_DIR="${SPECTRA_ROOT}/sdd/memory-bank/discovery"
ARCHIVE_ROOT="${DISCOVERY_DIR}/archive"
timestamp="$(date +%Y%m%d-%H%M%S)"

mkdir -p "${DISCOVERY_DIR}" "${ARCHIVE_ROOT}"

current_files=(
  "stack.md"
  "architecture.md"
  "structure.md"
  "conventions.md"
  "testing.md"
  "integrations.md"
  "concerns.md"
)

has_existing=0
for f in "${current_files[@]}"; do
  if [[ -f "${DISCOVERY_DIR}/${f}" && -s "${DISCOVERY_DIR}/${f}" ]]; then
    has_existing=1
    break
  fi
done

if [[ ${has_existing} -eq 1 ]]; then
  archive_dir="${ARCHIVE_ROOT}/${timestamp}"
  mkdir -p "${archive_dir}"
  for f in "${current_files[@]}"; do
    [[ -f "${DISCOVERY_DIR}/${f}" ]] || continue
    cp "${DISCOVERY_DIR}/${f}" "${archive_dir}/${f}"
  done
fi

detect_stack() {
  if [[ -f "${ROOT}/package.json" ]]; then
    echo "- Language: JavaScript/TypeScript (detected via package.json)"
  fi
  if [[ -f "${ROOT}/pyproject.toml" || -f "${ROOT}/requirements.txt" ]]; then
    echo "- Language: Python"
  fi
  if [[ -f "${ROOT}/go.mod" ]]; then
    echo "- Language: Go"
  fi
  if [[ -f "${ROOT}/Cargo.toml" ]]; then
    echo "- Language: Rust"
  fi
  if [[ -f "${ROOT}/pom.xml" || -f "${ROOT}/build.gradle" || -f "${ROOT}/build.gradle.kts" ]]; then
    echo "- Language: JVM"
  fi
  if [[ -f "${ROOT}/Gemfile" ]]; then
    echo "- Language: Ruby"
  fi

  return 0
}

top_dirs="$(find "${ROOT}" -maxdepth 1 -mindepth 1 -type d \
  ! -name '.git' ! -name 'node_modules' ! -name 'dist' ! -name 'build' ! -name '.next' \
  ! -name 'sdd' ! -name '.spectra' ! -name '.cursor' ! -name '.windsurf' ! -name '.agent' \
  -exec basename {} \; | sort | sed 's/^/- /')"

module_rows="$(find "${ROOT}" -maxdepth 1 -mindepth 1 -type d \
  ! -name '.git' ! -name 'node_modules' ! -name 'dist' ! -name 'build' ! -name 'spectra' ! -name '.spectra' \
  -exec basename {} \; | sort | awk '{ printf "| %s | Unconfirmed discovered directory | %s/ | |\\n", $0, $0 }')"

test_files="$(find "${ROOT}" -type f \( -name '*test*' -o -name '*spec*' -o -path '*/tests/*' -o -path '*/test/*' \) \
  ! -path '*/node_modules/*' ! -path '*/.git/*' ! -path '*/sdd/*' ! -path '*/.spectra/*' ! -path '*/.cursor/*' ! -path '*/.windsurf/*' ! -path '*/.agent/*' \
  | sed "s#${ROOT}/#- #" | sort | head -20)"

workflow_files="$(
  if [[ -d "${ROOT}/.github/workflows" ]]; then
    find "${ROOT}/.github/workflows" -type f | sed "s#${ROOT}/#- #" | sort
  fi
)"
todo_hits="$(rg -n "TODO|FIXME|XXX" "${ROOT}" \
  -g '!node_modules/**' -g '!.git/**' -g '!dist/**' -g '!build/**' \
  -g '!sdd/**' -g '!.cursor/**' -g '!.windsurf/**' -g '!.agent/**' \
  2>/dev/null | head -20 | sed 's#^#- #' || true)"

stack_signals="$(detect_stack)"
architecture_signals="$(
  for dir in app docs scripts src lib cmd internal; do
    if [[ -d "${ROOT}/${dir}" ]]; then echo "- ${dir}/ exists; responsibility unconfirmed"; fi
  done
  for file in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do
    if [[ -f "${ROOT}/${file}" ]]; then echo "- Container orchestration file: ${file}"; fi
  done
)"
convention_signals="$(
  for file in .editorconfig package.json Makefile .prettierrc eslint.config.js checkstyle.xml; do
    if [[ -f "${ROOT}/${file}" ]]; then echo "- ${file} present; conventions require review"; fi
  done
)"
integration_signals="$(
  for file in Dockerfile .env.example .env .gitlab-ci.yml Jenkinsfile azure-pipelines.yml; do
    if [[ -f "${ROOT}/${file}" ]]; then echo "- ${file} present; integration behavior unconfirmed"; fi
  done
)"

cat > "${DISCOVERY_DIR}/stack.md" <<EOF
# Discovery Stack

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Signals
${stack_signals:-"- No supported stack signals detected; review project manifests manually."}
EOF

cat > "${DISCOVERY_DIR}/architecture.md" <<EOF
# Discovery Architecture

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Signals
${architecture_signals:-"- No supported architecture layout signals detected; review source layout and manifests manually."}
EOF

cat > "${DISCOVERY_DIR}/structure.md" <<EOF
# Discovery Structure

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Top-Level Directories
${top_dirs:-"- (none detected)"}
EOF

cat > "${DISCOVERY_DIR}/conventions.md" <<EOF
# Discovery Conventions

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Signals
${convention_signals:-"- No supported convention signals detected; coding practices require review."}
EOF

cat > "${DISCOVERY_DIR}/testing.md" <<EOF
# Discovery Testing

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Test Files
${test_files:-"- No test files detected with simple heuristics"}
EOF

cat > "${DISCOVERY_DIR}/integrations.md" <<EOF
# Discovery Integrations

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Automation
${workflow_files:-"- No GitHub workflow files detected"}

## Runtime Signals
${integration_signals:-"- No supported integration signals detected; external integrations require review."}
EOF

cat > "${DISCOVERY_DIR}/concerns.md" <<EOF
# Discovery Concerns

> Unconfirmed findings generated by \`map-codebase.sh\`.

## Potential Follow-Ups
${todo_hits:-"- No TODO/FIXME markers detected with simple heuristics"}

## Reminder
- Treat discovery output as unconfirmed until intake or discussion records it explicitly.
EOF

mkdir -p "${SPECTRA_ROOT}/sdd/memory-bank/tech" "${SPECTRA_ROOT}/sdd/memory-bank/business"
if [[ "${PRESERVE_REVIEWED}" != "true" || ! -f "${SPECTRA_ROOT}/sdd/memory-bank/tech/modules.md" ]]; then
cat > "${SPECTRA_ROOT}/sdd/memory-bank/tech/modules.md" <<EOF
# Technical Module Index

> Unconfirmed bootstrap map generated by \`map-codebase.sh\`. Review before relying on it for routing.

| Module | Responsibility | Paths | Business Domains |
| --- | --- | --- | --- |
${module_rows:-"| (none) | No top-level modules detected | | |"}
EOF
fi

if [[ "${PRESERVE_REVIEWED}" != "true" || ! -f "${SPECTRA_ROOT}/sdd/memory-bank/business/INDEX.md" ]]; then
cat > "${SPECTRA_ROOT}/sdd/memory-bank/business/INDEX.md" <<EOF
# Business Domain Index

> Candidate domains are intentionally empty at bootstrap. Add only reviewed business domains; do not infer business truth from directory names.

| Domain | Keywords | Rules | Unresolved | Related Modules |
| --- | --- | --- | --- | --- |
EOF
fi

echo "Codebase mapping: OK"
