apiVersion: spectra/v2
kind: ApprovalState
current_state: implementation-approved
highest_valid_state: implementation-approved
stages:
  product-approved:
    approved_at: 2026-07-10T09:06:22.960Z
    baseline_commit: 13287b4fa51ec46d14590e87352f2169a1464dbe
    dirty: true
  technical-approved:
    approved_at: 2026-07-10T09:06:23.691Z
    baseline_commit: 13287b4fa51ec46d14590e87352f2169a1464dbe
    dirty: true
  implementation-approved:
    approved_at: 2026-07-10T09:27:07.785Z
    baseline_commit: 67e7b52a21aeea7d81518e8d4955f26506dcae29
    dirty: true
  release-approved:
    approved_at: null
    baseline_commit: null
    dirty: false
invalidations: []
